EcommerceProject2/EcommerceProject2/Controllers/AdminController.cs
using EcommerceProject2.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EcommerceProject2.Controllers
{
   
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            var entities = new EcommerceDBEntities();

            var categoryList = entities.Category
                    .SqlQuery("Select * from Category")
                    .ToList<Category>();

            TempData["categories"] = categoryList;
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {


            var entities = new EcommerceDBEntities();

            if (string.IsNullOrEmpty(admin.Admin_name) || string.IsNullOrEmpty(admin.Admin_pssw))
            {
                ViewBag.error = "Username and Password cannot be left blank!";
                return View();
            }

            var parameter3 = new SqlParameter("@Name", admin.Admin_name);
            var parameter4 = new SqlParameter("@passw", admin.Admin_pssw);
            var ad = entities.Admin.SqlQuery("SELECT * FROM Admin WHERE Admin_name= @Name AND Admin_pssw = @passw ", parameter3, parameter4).FirstOrDefault();


            if (ad != null)
            {
                FormsAuthentication.SetAuthCookie(admin.Admin_name, false);
                Session["Admin_id"] = ad.Admin_id.ToString();
                Session["Admin_name"] = ad.Admin_name.ToString();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.error = "Invalid Email or Password!";

            }
            return View();
        }


        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Clear(); // Oturum verilerini temizle
            Session.Abandon(); // Oturumu sonlandır
            return RedirectToAction("Login");
        }


        public ActionResult Category()
        {
            if (Session["Admin_id"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Category(Category cat, HttpPostedFileBase imgFile)
        {
            String path = uploadimage(imgFile);
            if (path.Equals("-1"))
            {
                ViewBag.error = "Image could not be uploaded";
            }
            else
            {
                using (var entities = new EcommerceDBEntities())
                {
                    string category = "INSERT INTO Category(Category_name,Category_image,Category_Desc,Category_admin_id) VALUES(@catName,@path,@desc,@id)";

                    int noOfRowInserted = entities.Database.ExecuteSqlCommand(category,
                        new SqlParameter("@catName", cat.Category_name),
                         new SqlParameter("@desc", cat.Category_Desc),
                        new SqlParameter("@path", cat.Category_image = path),
                        new SqlParameter("@id", cat.Category_admin_id = Convert.ToInt32(Session["Admin_id"].ToString())));



                    

                }
            }
            return RedirectToAction("Index"); 
        }


        [HttpGet]
        public ActionResult DeleteCategory()
        {

            return View();
        }

        [HttpPost]
        public ActionResult DeleteCategory(int CategoryID)
        {
            using (EcommerceDBEntities entities = new EcommerceDBEntities())
            {
                //var product = entities.Products.Find(productID);

                string deleteProductsQuery = "DELETE FROM Products WHERE Category_id = @CategoryID";
                SqlParameter categoryIDParam = new SqlParameter("@CategoryID", CategoryID);
                entities.Database.ExecuteSqlCommand(deleteProductsQuery, categoryIDParam);

                string deleteCategoryQuery = "DELETE FROM Category WHERE Category_id = @CategoryID";
                entities.Database.ExecuteSqlCommand(deleteCategoryQuery, categoryIDParam);

                return RedirectToAction("Index");
            }

        }

        public ActionResult Inventory()
        {
            var entities = new EcommerceDBEntities();

            var InventoryList = entities.Inventory_Table
                    .SqlQuery("SELECT * FROM Inventory_Table")
                    .ToList<Inventory_Table>();

            TempData["Inventory"] = InventoryList;

            return View();
        }


        //UPLOAD IMAGE CODE//
        public string uploadimage(HttpPostedFileBase file)
        {
            Random r = new Random();

            string path = "-1";

            int random = r.Next();

            if (file != null && file.ContentLength > 0)
            {
                string extension = Path.GetExtension(file.FileName);
                if (extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".png"))
                {
                    try
                    {
                        string filename = random + Path.GetFileName(file.FileName);
                        string serverPath = Server.MapPath("~/Content/Images/");
                        path = Path.Combine(serverPath, filename);
                        file.SaveAs(path);
                        path = "Content/Images/" + filename;
                    }
                    catch (Exception ex)
                    {
                        path = "-1";

                        throw;
                    }
                }

                else
                {
                    Response.Write("<script>alert('Only .JPG , .JPEG , .PNG Formats Are Allowed')</script>");
                }

            }

            else
            {
                Response.Write("<script>alert('Please Select a File')</script>");

                path = "-1";
            }

            return path;
        }

    }
}

EcommerceProject2/EcommerceProject2/Controllers/CartController.cs
using EcommerceProject2.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Xml.Linq;

namespace EcommerceProject2.Controllers
{
    public class CartController : Controller
    {

        // GET: Cart
        public ActionResult GetOrderCartItems()
        {
            int customerId = GetCustomerId();
            if(customerId == 0)
            {
                ViewBag.TotalPrice = "There are no products in your cart.";
            }
            else if (customerId != 0)
            {
                CalculateTotalPrice(customerId);

                using (var entities = new EcommerceDBEntities())
                {
                    //This SQL query command combines the Order_Cart_Table and Products tables to retrieve the customer's order card items.
                    string query = @"SELECT o.* , p.* FROM Order_Cart_Table o JOIN Products p ON o.Product_id = p.Product_id WHERE o.Customer_id = @CustomerId";
                    var orderCartItems = entities.Database.SqlQuery<Order_Cart_Table>(query, new SqlParameter("@CustomerId", customerId)).ToList();

                    //With this loop, get the associated product using a separate SQL query for each order card item. With this command we can reach the Product name with "@item.Products.Product_name"
                    foreach (var CartItem in orderCartItems)
                    {
                        string productQuery = @"SELECT * FROM Products WHERE Product_id = @ProductId";
                        var product = entities.Database.SqlQuery<Products>(productQuery, new SqlParameter("@ProductId", CartItem.Product_id)).FirstOrDefault();
                        CartItem.Products = product;
                    }
                    /* The LINQ Command equivalent of SQL Query 
                        var orderCartItems = entities.Order_Cart_Table
            .Where(o => o.Customer_id == customerId)
            .Include(o => o.Products)
            .ToList();*/

                    return View(orderCartItems);
                }
            }
            return View();
        }

        // POST: Cart/AddToOrderCart
        [HttpPost]
        public ActionResult AddToOrderCart(int productId, int amount, int price)
        {
            int customerId = GetCustomerId();
            if (customerId != 0)
            {

                using (var entities = new EcommerceDBEntities())
                {
                    

                    var orderCart = new Order_Cart_Table
                    {
                        Customer_id = customerId,
                        Order_Total = 0
                    };
                    var parameters = new SqlParameter[]
                    {
                            new SqlParameter("@ProductId", productId),
                            new SqlParameter("@Quantity", amount),
                            new SqlParameter("@CustomerId", customerId),
                            new SqlParameter("@Total",price)
                    };

                    // Ürün var mı diye kontrol etmek için SQL sorgusu
                    string checkQuery = "SELECT COUNT(*) FROM Order_Cart_Table WHERE Product_id = @ProductId AND Customer_id = @CustomerId";

                    int itemCount = entities.Database.SqlQuery<int>(checkQuery, parameters).FirstOrDefault();


                    if (itemCount == 0)
                    {
                        // Ürün sepette yok, ekleme işlemi için SQL sorgusu
                        string insertQuery = "INSERT INTO Order_Cart_Table (Product_id, Amount, Customer_id,Order_Total) VALUES (@ProductId, @Quantity,@CustomerId, @Total)";
                        entities.Database.ExecuteSqlCommand(insertQuery, new SqlParameter("@ProductId", productId),
                        new SqlParameter("@Quantity", amount),
                        new SqlParameter("@CustomerId", customerId),
                        new SqlParameter("@Total", price)
                        );

                    }
                    else
                    {
                        // Ürün zaten sepette, güncelleme işlemi için SQL sorgusu
                        string updateQuery = "UPDATE Order_Cart_Table SET Amount = Amount + @Quantity, Order_Total = @Total WHERE Product_id = @ProductId AND Customer_id = @CustomerId";
                        entities.Database.ExecuteSqlCommand(updateQuery, new SqlParameter("@ProductId", productId),
                         new SqlParameter("@Quantity", amount),
                         new SqlParameter("@CustomerId", customerId),
                         new SqlParameter("@Total", price)
                         );
                    }

                    decimal? totalPrice = CalculateTotalPrice(customerId);
                    ViewBag.CustomerName = customerId;
                    ViewBag.TotalPrice = totalPrice;

                   

                    return RedirectToAction("Index","Home");
                   
                }
            }
                return RedirectToAction("Login","Customer");
         
        }

        // POST: Cart/RemoveFromOrderCart
        [HttpPost]
        public ActionResult RemoveFromOrderCart(int orderCartId)
        {
            
            using (var entities = new EcommerceDBEntities())
            {
                string query2 = "DELETE FROM Order_Table WHERE Order_Cart_id = @OrderCartID";
                entities.Database.ExecuteSqlCommand(query2, new SqlParameter("@OrderCartID", orderCartId));
            }

            using (var entities = new EcommerceDBEntities())
            {
                var orderCart = entities.Order_Cart_Table.Find(orderCartId);

                if (orderCart != null)
                {
                    if (orderCart.Amount > 1)
                    {
                        orderCart.Amount--;
                        entities.SaveChanges();
                    }
                    else
                    {
                        string query = "DELETE FROM Order_Cart_Table WHERE Order_Cart_id = @OrderCartId";
                        entities.Database.ExecuteSqlCommand(query, new SqlParameter("@OrderCartId", orderCartId));

                    }
                }
            }
            int customerId = GetCustomerId();
            
            return RedirectToAction("GetOrderCartItems");
        }

        public ActionResult TotalCount()
        {
            using (var entities = new EcommerceDBEntities())
            {
                if (User.Identity.IsAuthenticated)
                {
                    int customerId = GetCustomerId();
                    var queryy = "SELECT COUNT(Order_Cart_id) FROM Order_Cart_Table WHERE Customer_id =@customerId ";
                    int count = entities.Database.SqlQuery<int>(queryy, new SqlParameter("@customerId", customerId)).FirstOrDefault();

                    ViewBag.Count = count;

                    Debug.WriteLine($"CustomerId: {customerId}");
                    Debug.WriteLine($"Count: {count}");
                }
            }
            return PartialView();
        }

        private decimal? CalculateTotalPrice(int customerId)
        {

            using (var entities = new EcommerceDBEntities())
            {
                var parameters = new SqlParameter[]
                {
                    new SqlParameter("@CustomerId", customerId)
                    };

                string totalPriceQuery = "SELECT CAST(SUM(p.price * s.Amount) AS DECIMAL(18, 2)) FROM Order_Cart_Table s INNER JOIN Products p ON s.Product_id = p.Product_id WHERE s.Customer_id = @CustomerId";

                decimal? totalPrice = entities.Database.SqlQuery<decimal?>(totalPriceQuery, parameters).FirstOrDefault();

                if (totalPrice.HasValue && totalPrice != 0)
                {
                    ViewBag.TotalPrice = totalPrice.Value;
                    return totalPrice.Value;

                }
                else
                {
                    ViewBag.TotalPrice ="There are no products in your cart.";
                }

                return 0;
            }


        }
        private int GetCustomerId()
        {
            int customerId = 0;
            if (Session["Customer_id"] != null && int.TryParse(Session["Customer_id"].ToString(), out customerId))
            {
                return customerId;
            }
            return 0;
        }

        public ActionResult OrderComplete()
        {
          
           return View();
        }

        }
    }

EcommerceProject2/EcommerceProject2/Views/Shared/_Layout.cshtml
@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <title>@ViewBag.Title - GGEZ Official Online Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GGEZ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" style="font-size:16px">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>


                    @{
                        if (isLoggedIn)
                        {
                            if (Session["Admin_id"] != null && Session["Customer_id"] == null)
                            {
                                <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                                <li>@Html.ActionLink("Stocks", "Inventory", "Admin")</li>
                                <li>@Html.ActionLink("Categories", "Index", "Admin")</li>
                                <li>@Html.ActionLink("Add Products", "Products", "Products")</li>
                                <li>@Html.ActionLink("Products", "Index", "Products")</li>
                                <li style="position: relative; left: 695px;">@Html.ActionLink(User.Identity.Name, "AdminContact", "Home", new { id = Convert.ToInt32(Session["Admin_id"].ToString()) }, null)</li>
                                <li style="position: relative; left: 700px;">@Html.ActionLink("Log Out", "LogOut", "Admin")</li>

                            }
                            if (Session["Customer_id"] != null)
                            {

                                <li>
                                    <a class="navbar-link px-lg-4" href="~/Cart/GetOrderCartItems"><img src="~/Content/Images/cart.png" width="30" height="30" /> &nbsp; @{ Html.RenderAction("TotalCount", "Cart");}</a>   
                                </li>
                                <li style="position: relative; left: 895px;">@Html.ActionLink(User.Identity.Name, "Contact", "Home", new {id = Convert.ToInt32(Session["Customer_id"].ToString()) },null)</li>
                                <li style="position: relative; left: 900px;">@Html.ActionLink("Log Out", "LogOut", "Customer")</li>

                            }
                        }
                        else
                        {
                            <li> @Html.ActionLink("Admin Login", "Login", "Admin")</li>
                            <li style="float:right">@Html.ActionLink("Customer Login", "Login", "Customer")</li>
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GGEZ Group Consulting Communication and Sales Trade.A.Sh.- All Rights Reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

EcommerceProject2/EcommerceProject2/Views/Shared/_Layout_Admin.cshtml
@{
    bool isLoggedIn = true;
    if (string.IsNullOrWhiteSpace(User.Identity.Name))
    {
        isLoggedIn = false;
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -  GGEZ Official Online Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GGEZ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>


                    @{
                        if (Session["Admin_id"] != null)
                        {
                            <li>@Html.ActionLink("Orders", "Index", "Orders")</li>
                            <li>@Html.ActionLink("Stocks", "Inventory", "Admin")</li>
                            <li>@Html.ActionLink("Categories", "Index", "Admin")</li>
                            <li>@Html.ActionLink("Add Products", "Products", "Products")</li>
                            <li>@Html.ActionLink("Products", "Index", "Products")</li>
                            <li style="position: relative; left: 695px;">@Html.ActionLink(User.Identity.Name, "AdminContact", "Home", new { id = Convert.ToInt32(Session["Admin_id"].ToString()) }, null)</li>
                            <li style="position: relative; left: 700px;">@Html.ActionLink("Log Out", "LogOut", "Admin")</li>

                        }
                        if (Session["Admin_id"] == null && Session["Customer_id"] == null)
                        {
                            <li>@Html.ActionLink("Admin Login", "Login", "Admin")</li>
                            <li>@Html.ActionLink("Customer Login", "Login", "Customer")</li>
                        }

                        if (Session["Customer_id"] != null)
                        {
                           
                            <li>@Html.ActionLink("Cart", "GetOrderCartItems", "Cart")</li>
                            <li style="position: relative; left: 795px;">@Html.ActionLink(User.Identity.Name, "Contact", "Home", new { id = Convert.ToInt32(Session["Customer_id"].ToString()) })</li>
                            <li style="position: relative; left: 800px;">@Html.ActionLink("Log Out", "LogOut", "Customer")</li>

                        }
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GGEZ Group Consulting Communication and Sales Trade.A.Sh.- All Rights Reserved.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>